version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: 800762100828.dkr.ecr.ap-south-1.amazonaws.com

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - docker build -t webapp .
      - docker tag webapp:latest 800762100828.dkr.ecr.ap-south-1.amazonaws.com/webapp:latest
      - docker push 800762100828.dkr.ecr.ap-south-1.amazonaws.com/webapp:latest
      - echo pushed to ECR repository